from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class IntentModel(BaseModel):
    """
    Minimal representation of the intent associated with a
    conversation turn.

    M2 only stores the intent. It does not determine the intent.
    Intent resolution belongs to later reasoning work.
    """

    name: str
    description: str | None = None


class ConversationEntry(BaseModel):
    """
    One conversational turn.

    Stores what happened in the conversation together with the
    understanding metadata available for that turn.
    """

    user_input: str = Field(
        ...,
        description="The input provided by the user.",
    )

    assistant_response: str | None = Field(
        None,
        description="The response generated by the assistant.",
    )

    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="Time at which this conversation entry was created.",
    )

    intent: IntentModel | None = Field(
        None,
        description="The intent associated with the user input, if known.",
    )

    confidence_score: float | None = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Confidence in the understanding of the user input.",
    )

    feedback: str | None = Field(
        None,
        description="Optional feedback associated with the assistant response.",
    )


class ActiveTopic(BaseModel):
    """
    The currently active conversational topic/entity.

    M2 stores the state only. The mechanism that determines or updates
    relevance belongs to later reasoning milestones.
    """

    entity: str
    relevance_score: float = Field(
        1.0,
        ge=0.0,
        le=1.0,
        description="Current relevance of the active entity.",
    )


class PendingClarification(BaseModel):
    """
    Clarification currently waiting for an answer from the user.
    """

    clarification_question: str = Field(
        ...,
        description="The clarification question presented to the user.",
    )


class PendingRequest(BaseModel):
    """
    The incomplete request that caused clarification to be required.

    This allows a later user answer to be combined with the original
    request instead of being interpreted as a completely new request.
    """

    intent: IntentModel | None = Field(
        None,
        description="The intent of the incomplete request.",
    )

    missing_information: list[str] = Field(
        default_factory=list,
        description="Information still required to complete the request.",
    )

    clarification_answer: str | None = Field(
        None,
        description="The user's answer to the clarification.",
    )


class ConversationContext(BaseModel):
    """
    Persistent state belonging to one JARVIS conversation.

    This is deliberately separate from ExecutionContext.

    ConversationContext:
        Persists across turns and stores conversational state.

    ExecutionContext:
        Exists for a request and stores execution/tool state.
    """

    conversation_id: UUID = Field(
        default_factory=uuid4,
        description="Unique identifier for the conversation.",
    )

    conversation_history: list[ConversationEntry] = Field(
        default_factory=list,
        description="Conversation history across turns.",
    )

    active_topic: list[ActiveTopic] | None = Field(
        None,
        description="Currently active conversational entity/topic.",
    )

    pending_clarification: PendingClarification | None = Field(
        None,
        description="Clarification currently awaiting a user response.",
    )

    pending_request: PendingRequest | None = Field(
        None,
        description="Incomplete request associated with the clarification.",
    )

    resolved_references: list[str] = Field(
        default_factory=list,
        description="References that have been resolved during the conversation.",
    )

    last_assistant_response: str | None = Field(
        None,
        description="The most recent response generated by the assistant.",
    )